version: '3.7'
services:
    dbmysql:
        image: mysql
        restart: always
        environment:
          - MYSQL_DATABASE=root
          - MYSQL_ROOT_PASSWORD=password
        ports:
          - 3306:3306
        volumes: 
          # Copy the sql script to create tables
          - ./mysql/seed.sql:/docker-entrypoint-initdb.d/seed.sql          
    node:
        build: .
        ports:
          - 8080:3000
        environment:
          - PGUSER=postgres
          - PGDATABASE=pa
          - PGHOST=dbpg
          - PGPASSWORD=postgres
          - PGPORT=5432
        depends_on:
          - dbmysql