version: '3.7'
services:
    dbmysql:
        image: mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=event_tracker
        ports:
          - 3306:3306
        volumes:
          - ./seed:/docker-entrypoint-initdb.d        
    node:
        build: .
        ports:
          - 8080:3000
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=event_tracker
          - MYSQL_HOST=dbmysql
          - MYSQL_PORT=3306
        depends_on:
          - dbmysql